package gooei.input;

public enum Keys
{

NONE,

TAB,

ESCAPE,
RETURN,
RIGHT,
LEFT,
UP,
DOWN,

HOME,
END,
PRIOR,
NEXT,

BACK,
DELETE,

MINUS, EQUALS, LBRACKET, RBRACKET, LCONTROL, RCONTROL,
SEMICOLON, APOSTROPHE, GRAVE, LSHIFT,
COMMA, PERIOD, SLASH, RSHIFT, MULTIPLY, LMENU, SPACE, CAPITAL,
NUMLOCK, SCROLL,
NUMPAD0, NUMPAD1, NUMPAD2, NUMPAD3, NUMPAD4, NUMPAD5, NUMPAD6, NUMPAD7,
NUMPAD8, NUMPAD9, 
SUBTRACT, ADD, DECIMAL,
KANA, CONVERT, NOCONVERT, YEN, NUMPADEQUALS,
CIRCUMFLEX, AT, COLON, UNDERLINE, KANJI, STOP,
AX, UNLABELED, NUMPADENTER, NUMPADCOMMA,
DIVIDE, SYSRQ, RMENU, PAUSE, LWIN, RWIN, APPS,
POWER, SLEEP, INSERT, 

F1, F2, F3, F4, F5, F6, F7, F8, F9, F10,
F11, F12, F13, F14, F15,

A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
BACKSLASH,
D1, D2, D3, D4, D5, D6, D7, D8, D9, D0;

public char charRepresentation()
{ return 0; }

}
